SELECT N.YEAR, (MAX_SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA AS E 
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
           MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR 
) AS N 
ON YEAR(E.DIFFERENTIATION_DATE) = N.YEAR
ORDER BY YEAR, YEAR_DEV;


