SELECT ID, FISH_NAME, LENGTH 
FROM FISH_NAME_INFO AS N
JOIN FISH_INFO AS I
ON N.FISH_TYPE = I.FISH_TYPE
WHERE I.LENGTH IN (
    SELECT MAX(LENGTH)
    FROM FISH_INFO
    WHERE FISH_TYPE = I.FISH_TYPE
    GROUP BY FISH_TYPE
)
ORDER BY I.ID;

